packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  dev:
    '@antfu/eslint-config': ^6.0.0
    '@antfu/ni': ^27.0.0
    '@antfu/utils': ^9.3.0
    '@types/node': ^24.9.1
    bumpp: ^10.3.1
    czg: ^1.12.0
    eslint: ^9.38.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.5
    simple-git-hooks: ^2.13.1
    stylelint: ^16.25.0
    taze: ^19.8.1
    tsdown: ^0.15.9
    tsx: ^4.20.6
    typescript: ^5.9.3
    vite: ^7.1.11
    vitest: ^3.2.4
  docs:
    '@iconify-json/svg-spinners': ^1.2.4
    '@shikijs/vitepress-twoslash': ^3.13.0
    '@unocss/reset': ^66.5.4
    '@vueuse/core': ^13.9.0
    floating-vue: ^5.2.2
    pinia: ^3.0.3
    unocss: ^66.5.4
    unplugin-vue-components: ^30.0.0
    vite-tsconfig-paths: ^5.1.4
    vitepress: ^2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.4
    vue: ^3.5.22

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

verifyDepsBeforeRun: install
