packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  dev:
    '@antfu/eslint-config': ^5.4.1
    '@antfu/ni': ^26.1.0
    '@antfu/utils': ^9.3.0
    '@types/node': ^24.7.1
    bumpp: ^10.3.1
    czg: ^1.12.0
    eslint: ^9.37.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.3
    simple-git-hooks: ^2.13.1
    stylelint: ^16.25.0
    taze: ^19.7.0
    tsdown: ^0.15.6
    tsx: ^4.20.6
    typescript: ^5.9.3
    vite: ^7.1.9
    vitest: ^3.2.4
  docs:
    '@iconify-json/svg-spinners': ^1.2.4
    '@shikijs/vitepress-twoslash': ^3.13.0
    '@unocss/reset': ^66.5.2
    '@vueuse/core': ^13.9.0
    floating-vue: ^5.2.2
    pinia: ^3.0.3
    unocss: ^66.5.2
    unplugin-vue-components: ^29.1.0
    vite-tsconfig-paths: ^5.1.4
    vitepress: ^2.0.0-alpha.12
    vitepress-plugin-group-icons: ^1.6.3
    vue: ^3.5.22

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

verifyDepsBeforeRun: install
ignoreWorkspaceRootCheck: true
