packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  dev:
    '@antfu/eslint-config': ^5.2.1
    '@antfu/ni': ^25.0.0
    '@antfu/utils': ^9.2.0
    '@types/node': ^24.3.0
    bumpp: ^10.2.3
    czg: ^1.12.0
    eslint: ^9.33.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
    stylelint: ^16.23.1
    taze: ^19.1.1
    tinyexec: ^1.0.1
    tsx: ^4.20.4
    typescript: ^5.9.2
    unbuild: ^3.6.1
    vite: ^7.1.3
    vitest: ^3.2.4
  docs:
    '@iconify-json/svg-spinners': ^1.2.4
    '@shikijs/vitepress-twoslash': ^2.5.0
    '@unocss/reset': ^66.4.2
    '@vueuse/core': ^12.8.2
    floating-vue: ^5.2.2
    pinia: ^3.0.3
    unocss: ^66.4.2
    unplugin-vue-components: ^28.8.0
    vite-tsconfig-paths: ^5.1.4
    vitepress: ^2.0.0-alpha.11
    vitepress-plugin-group-icons: ^1.6.3
    vue: ^3.5.18
