[env]
_.path = ["./node_modules/.bin"]

[tasks.dev]
run = "tsdown --watch"

[tasks.build]
run = "tsdown"

[tasks.start]
run = "bun ./src/index.ts"

[tasks.publish]
run = [
  "bun pm pack --filename {{ config_root }}/release.tgz",
  "npm publish {{ config_root }}/release.tgz --access public --tag latest",
]
