[env]
_.path = [ "./node_modules/.bin" ]

[tasks.dev]
run = "aubr dev"

[tasks.build]
run = "aubr build"

[tasks.start]
run = "aubr start"

[tasks.typecheck]
depends = "//:build"
run = "aubr typecheck"
